feat: Add contact page
lenra-io/website pull request #63
Opened 2023-01-23 17:00 UTC by taorepoara

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [x] I made my own code-review before requesting one

## Description of the changes
Add the contact page to the website.

## Technical highlight/advice
Make the contact form bot-proof

2023-04-25 08:26 UTC, jonas-martinez requested changes
I think that this PR is clearly over-scoped, why remove k8s files ?

2023-04-26 10:20 UTC, taorepoara commented
> I think that this PR is clearly over-scoped, why remove k8s files ?

I've readded them and removed them in another PR: https://github.com/lenra-io/website/pull/83

2023-04-26 10:55 UTC, jonas-martinez approved these changes

2023-04-26 10:55 UTC, merged

2023-04-26 10:58 UTC, taorepoara commented
:tada: This PR is included in version 1.1.0-beta.6 :tada:

The release is available on:
- [GitHub release](https://github.com/lenra-io/website/releases/tag/v1.1.0-beta.6)
- `v1.1.0-beta.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: